### ISSUE TITLE
ERROR when  sudo go get github.com/kahing/goofys

### ISSUE THREAD

**Issue by Mitchell-kw-Lee** [kahing/goofys#451]
This happening now.

# github.com/kahing/goofys/internal
/root/go/src/github.com/kahing/goofys/internal/backend_adlv2.go:251:13: undefined: strings.Builder
/root/go/src/github.com/kahing/goofys/internal/backend_adlv2.go:563:10: undefined: strings.Builder

**Comment by kahing** [comment]
what version of go are you using?

**Comment by Mitchell-kw-Lee** [comment]
go version go1.9.4 linux/amd64 that on AWS

**Comment by Mitchell-kw-Lee** [comment]
Is there any workaround? since urgent.

**Comment by Mitchell-kw-Lee** [comment]
This is the workaround. Thanks for pointing out.

$ go version
$ amazon-linux-extras list | grep golang
$ sudo amazon-linux-extras install golang1.11
$ go version

**Comment by dprestegard** [comment]
Does this mean golang 1.11 is now required? The readme still says 1.9 is sufficient. I'm having this issue now with golang 1.9.2 on debian stretch

**Comment by Htarlov** [comment]
As of April 2021 most likely 1.13 is needed (errors.Is is not present in earlier versions) and I just checked that it surely works on 1.16.
